/* TourGuard AI browser client. No frameworks are required for the local edition. */
const state = { token: localStorage.getItem('tg_token'), user: null, page: 'dashboard', dark: localStorage.getItem('tg_theme') === 'dark', dashboard: null, gates: [], stream: null, passItems: new Map() };
const app = document.getElementById('app');
const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const esc = (value) => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const num = (value) => Number(value || 0).toLocaleString();
const isEditor = () => state.user && ['admin', 'operator'].includes(state.user.role);
const isAdmin = () => state.user?.role === 'admin';
function printVisitorPass(pass) {
  if (!pass?.parentElement) return;
  const parent = pass.parentElement;
  const nextSibling = pass.nextSibling;
  const restore = () => {
    document.body.classList.remove('printing-pass');
    if (parent.isConnected) parent.insertBefore(pass, nextSibling?.parentNode === parent ? nextSibling : null);
  };
  document.body.classList.add('printing-pass');
  document.body.append(pass);
  window.addEventListener('afterprint', restore, { once: true });
  window.print();
}
document.addEventListener('click', event => {
  const button = event.target.closest('#print-pass, #print-saved-pass');
  if (!button) return;
  event.preventDefault();
  event.stopImmediatePropagation();
  printVisitorPass($('#visitor-pass'));
}, true);
const api = async (url, options = {}) => {
  const response = await fetch(url, { ...options, headers: { 'Content-Type': 'application/json', ...(state.token ? { Authorization: `Bearer ${state.token}` } : {}), ...(options.headers || {}) } });
  let data; try { data = await response.json(); } catch { data = {}; }
  if (!response.ok) { const error = new Error(data?.error?.message || 'Something went wrong.'); error.data = data; error.status = response.status; throw error; }
  return data;
};
function toast(message, type = 'success') { const el = document.createElement('div'); el.className = `toast ${type === 'error' ? 'error' : type === 'warn' ? 'warn' : ''}`; el.textContent = message; $('#toast-stack').append(el); setTimeout(() => el.remove(), 4300); }
app.addEventListener('click', event => { const button = event.target.closest('[data-pass-id]'); if (!button) return; const item = state.passItems.get(String(button.dataset.passId)); if (item) showStoredPass(item); });
function dateTime(value) { if (!value) return '—'; try { return new Intl.DateTimeFormat(undefined, { dateStyle:'medium', timeStyle:'short' }).format(new Date(value)); } catch { return value; } }
function roleName(role) { return ({admin:'Administrator', operator:'Gate Operator', viewer:'Viewer / Manager'})[role] || role; }
function badge(status) { const cls = String(status || '').toLowerCase(); return `<span class="badge ${cls}">${esc(status)}</span>`; }
function vehicleIcon(type) { return ({Car:'▰',Bike:'◉',Bus:'▰',Auto:'◒',Van:'▱',Other:'◇'})[type] || '◇'; }
function setLoading(label = 'Loading secure workspace…') { app.innerHTML = `<div class="loading">${esc(label)}</div>`; }

const nav = [
  ['dashboard','⌂','Dashboard'], ['entry','＋','Tourist Entry'], ['exit','⇥','Tourist Exit'], ['inside','♟','Currently Inside'], ['history','▤','Visitor History'], ['vehicles','▱','Vehicles'], ['parking','▣','Parking'], ['analytics','▥','Analytics'], ['ai','✦','AI Insights'], ['reports','▧','Reports'], ['notifications','◉','Notifications'], ['users','♙','Users','admin'], ['settings','⚙','Settings','admin']
];
function shell(content) {
  document.body.classList.toggle('dark', state.dark);
  const navHtml = nav.map(([key, icon, title, restricted]) => `<button data-nav="${key}" class="${state.page === key ? 'active':''}"><span class="nav-icon">${icon}</span>${title}${restricted && !isAdmin() ? '<span class="restricted">ADMIN</span>' : ''}</button>`).join('');
  app.innerHTML = `<div class="app-shell"><aside class="sidebar" id="sidebar"><a class="brand" href="#dashboard"><span class="brand-mark">⌖</span>TourGuard AI</a><div><p class="sidebar-label">OPERATIONS</p><nav class="nav">${navHtml}</nav></div><div class="sidebar-bottom"><b>● Live system connected</b><span>Updates appear automatically</span></div></aside><main class="main"><header class="topbar"><button class="menu-toggle" id="menu-toggle" aria-label="Open menu">☰</button><div class="global-search"><input id="global-search" placeholder="Search vehicle, visitor ID, phone…" aria-label="Global search" /></div><div class="top-actions"><button class="icon-btn" id="theme-toggle" title="Toggle appearance">${state.dark ? '☼' : '◐'}</button><button class="icon-btn" id="notification-link" title="Notifications">◉</button><div class="user-chip"><div class="avatar">${esc(state.user.name.split(' ').map(x=>x[0]).join('').slice(0,2))}</div><div><b>${esc(state.user.name)}</b><small>${roleName(state.user.role)}</small></div></div><button class="icon-btn" id="logout" title="Sign out">⇥</button></div></header>${content}</main></div>`;
  $$('[data-nav]').forEach(btn => btn.addEventListener('click', () => go(btn.dataset.nav)));
  $('#theme-toggle').onclick = () => { state.dark = !state.dark; localStorage.setItem('tg_theme', state.dark ? 'dark' : 'light'); render(); };
  $('#notification-link').onclick = () => go('notifications');
  $('#logout').onclick = logout;
  $('#global-search').addEventListener('keydown', (event) => { if (event.key === 'Enter' && event.target.value.trim()) { state.page = 'history'; renderHistory({search:event.target.value.trim()}); } });
  $('#menu-toggle').onclick = () => { $('#sidebar').classList.add('open'); const overlay = document.createElement('div'); overlay.className='mobile-overlay'; overlay.onclick=()=>{ $('#sidebar').classList.remove('open'); overlay.remove(); }; document.body.append(overlay); };
}
function pageHeader(eyebrow, title, copy, actions = '') { return `<section class="page"><header class="page-header"><div><div class="eyebrow">${esc(eyebrow)}</div><h1>${esc(title)}</h1><p>${esc(copy)}</p></div><div class="page-actions">${actions}</div></header>${state.dashboard?.demo_mode ? '<div class="demo-banner">◈ <span><b>Demo workspace</b> — seeded records are clearly separate from your live operations.</span></div>' : ''}`; }
function endPage() { return '</section>'; }
function notAllowed(title='This area is for administrators') { shell(pageHeader('Restricted', title, 'Your viewer role can access dashboards and reports, but cannot modify configuration.') + `<div class="card empty"><div class="empty-icon">⌁</div><b>Administrator access required</b><p>Ask an administrator if you need access to this workflow.</p></div>` + endPage()); }
function barChart(data, tone='') { const max = Math.max(...data.map(x => x.value), 1); return `<div class="bar-chart ${tone}">${data.map(item => `<div class="bar-wrap"><i class="bar" style="height:${Math.max(3, item.value / max * 100)}%" data-value="${esc(item.label)}: ${num(item.value)}"></i></div>`).join('')}</div><div class="chart-labels">${data.map(item => `<span>${esc(item.label)}</span>`).join('')}</div>`; }

async function render() {
  if (!state.token) return renderLogin();
  try { if (!state.user) state.user = (await api('/api/auth/me')).user; } catch { return logout(); }
  setLoading();
  try {
    if (state.page === 'dashboard') return renderDashboard();
    if (state.page === 'entry') return renderEntry();
    if (state.page === 'exit') return renderExit();
    if (state.page === 'inside') return renderInside();
    if (state.page === 'history') return renderHistory();
    if (state.page === 'vehicles') return renderVehicles();
    if (state.page === 'parking') return renderParking();
    if (state.page === 'analytics') return renderAnalytics();
    if (state.page === 'ai') return renderAI();
    if (state.page === 'reports') return renderReports();
    if (state.page === 'notifications') return renderNotifications();
    if (state.page === 'users') return renderUsers();
    if (state.page === 'settings') return renderSettings();
    state.page = 'dashboard'; return renderDashboard();
  } catch (error) { shell(pageHeader('System notice','Could not load this page','The system protected your data while this request failed.') + `<div class="card empty"><div class="empty-icon">⚠</div><b>${esc(error.message)}</b><p>Check the local server connection and try again.</p><button class="primary-btn" onclick="location.reload()">Try again</button></div>` + endPage()); }
}
function go(page) { stopCameraScanner(); state.page = page; $('#sidebar')?.classList.remove('open'); $('.mobile-overlay')?.remove(); render(); }
async function loadDashboard() { state.dashboard = await api('/api/dashboard'); return state.dashboard; }

async function renderLogin() {
  app.innerHTML = `<div class="login-shell"><section class="login-art"><a class="brand" href="#"><span class="brand-mark">⌖</span>TourGuard AI</a><div class="login-hero"><div class="eyebrow">Smart visitor management</div><h1>Know who is in, in real time.</h1><p>One calm command center for visitor entry, exit, parking, crowd safety, and operational insight.</p><div class="feature-pills"><span>● Live occupancy</span><span>✦ Insight-ready</span><span>⌁ Secure roles</span></div></div><small>Built for high-visitor places — from forts to wildlife parks.</small></section><main class="login-panel"><form id="login-form" class="login-card"><div class="eyebrow">Welcome back</div><h2>Sign in to TourGuard</h2><p class="muted">Use your role-based account to continue.</p><div class="demo-box"><b>Demo accounts</b>Admin: admin@tourguard.local · Admin@123<br>Operator: gate@tourguard.local · Gate@123</div><div class="field"><label for="email">Email address</label><input id="email" type="email" required value="admin@tourguard.local" autocomplete="email"></div><div class="field"><label for="password">Password</label><input id="password" type="password" required value="Admin@123" autocomplete="current-password"></div><button class="login-submit" id="login-button" type="submit">Sign in securely <span>→</span></button><p class="muted" style="font-size:12px;text-align:center;margin-top:18px">Passwords are protected with PBKDF2 hashing and sessions expire automatically.</p></form></main></div>`;
  $('#login-form').onsubmit = async event => { event.preventDefault(); const btn=$('#login-button'); btn.disabled=true; btn.textContent='Signing in…'; try { const result=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:$('#email').value,password:$('#password').value})}); state.token=result.token; state.user=result.user; localStorage.setItem('tg_token', state.token); connectStream(); toast(`Welcome, ${state.user.name.split(' ')[0]}.`); render(); } catch(error){ toast(error.message,'error'); btn.disabled=false; btn.innerHTML='Sign in securely <span>→</span>'; } };
}
function logout() { stopCameraScanner(); state.stream?.close(); state.stream=null; localStorage.removeItem('tg_token'); state.token=null; state.user=null; state.dashboard=null; renderLogin(); toast('You have been signed out.'); }
function connectStream() { state.stream?.close(); if (!state.token) return; state.stream = new EventSource(`/api/stream?token=${encodeURIComponent(state.token)}`); state.stream.onmessage = () => { if (state.token) { loadDashboard().then(() => render()).catch(()=>{}); toast('Live data updated.'); } }; }

async function renderDashboard() {
  const d = await loadDashboard(), m = d.metrics;
  shell(pageHeader('Live overview','Good morning, ' + state.user.name.split(' ')[0], 'Here is the current picture across your gates.', `<button class="secondary-btn" id="refresh-dashboard">↻ Refresh</button>${isEditor()?'<button class="primary-btn" data-go="entry">＋ Register entry</button>':''}`) + `<div class="metric-grid">
    ${metric('Visitors today',m.total_visitors_today,'◉','Recorded entries today')}${metric('Currently inside',m.currently_inside,'♟',`${m.occupancy_percent}% of guest capacity`)}${metric('Exited today',m.exited_today,'⇥','Completed visits')}${metric('Vehicles inside',m.vehicles_inside,'▱',`${m.cars_inside} cars · ${m.bikes_inside} bikes`)}</div>
    <div class="content-grid"><section class="card chart-card"><div class="card-head"><div><h2>Visitor movement by hour</h2><p>Recorded entries across today and history</p></div><button class="secondary-btn" data-go="analytics">View analytics →</button></div>${barChart((await api('/api/analytics')).hourly)}</section><section class="card"><div class="card-head"><div><h2>Live activity</h2><p>Newest movement first</p></div><span class="badge inside">LIVE</span></div><div class="activity-list">${d.activity.map(a=>`<div class="activity-item"><i class="activity-dot ${a.status==='EXITED'?'exit':''}"></i><div><b>${esc(a.vehicle_number)} ${a.status==='EXITED'?'exited':'entered'}</b><span>${esc(a.group_name)} · ${a.status==='EXITED'?'Visit completed':'Currently inside'}</span></div><time class="activity-time">${dateTime(a.at).split(',').pop().trim()}</time></div>`).join('') || '<div class="empty">No activity yet.</div>'}</div></section></div>
    <div class="content-grid"><section class="card"><div class="card-head"><div><h2>Parking occupancy</h2><p>Live count from active entries</p></div><button class="secondary-btn" data-go="parking">Manage →</button></div><div class="parking-list">${d.parking.map(parkingRow).join('')}</div></section><section class="card"><div class="card-head"><div><h2>Crowd health</h2><p>Tourist capacity status</p></div>${badge(m.crowd_level)}</div><div style="padding:18px 19px"><div style="display:flex;align-items:baseline;gap:8px"><strong style="font-size:34px;letter-spacing:-2px">${num(m.currently_inside)}</strong><span class="muted">of ${num(m.max_capacity)} guests</span></div><div class="progress ${m.crowd_level.toLowerCase()}" style="margin:14px 0 10px"><i style="width:${Math.min(100,m.occupancy_percent)}%"></i></div><p class="muted" style="font-size:12px;margin:0">${crowdMessage(m)}</p></div></section></div>` + endPage());
  $('#refresh-dashboard').onclick=()=>renderDashboard(); $$('[data-go]').forEach(x=>x.onclick=()=>go(x.dataset.go));
}
function metric(label,value,icon,note){return `<article class="metric-card"><span class="metric-icon">${icon}</span><div class="metric-label">${label}</div><div class="metric-value">${num(value)}</div><div class="metric-note">${esc(note)}</div></article>`}
function parkingRow(p){const cls=p.percent>=100?'danger':p.percent>=80?'warn':'';return `<div class="parking-row"><header><span>${esc(p.vehicle_type)} parking</span><span>${p.occupied} / ${p.capacity}</span></header><div class="progress ${cls}"><i style="width:${Math.min(100,p.percent)}%"></i></div></div>`}
function crowdMessage(m){return m.crowd_level==='CRITICAL'?'Maximum capacity reached. Pause new entries until occupancy reduces.':m.crowd_level==='HIGH'?'High crowd warning. Consider routing visitors across gates.':m.crowd_level==='MEDIUM'?'Crowd is increasing. Monitor gate flow and parking.':'Crowd level is within the normal operating range.'}

async function gates() { if (!state.gates.length) state.gates=(await api('/api/gates')).items; return state.gates; }
async function renderEntry() {
  if (!isEditor()) return notAllowed('Entry registration requires operator access'); const gateList=await gates();
  shell(pageHeader('Gate operations','Register tourist entry','Date, time, visitor reference, and QR access token are created automatically.') + `<div class="card form-card" id="entry-view"><form id="entry-form" novalidate><div class="form-section">Visitor information</div><div class="form-grid"><div class="field"><label>Tourist / group name</label><input name="group_name" placeholder="e.g. Mehta Family" required></div><div class="field"><label>Mobile number <span class="muted">(optional)</span></label><input name="mobile" inputmode="tel" placeholder="e.g. 9876543210"></div><div class="field"><label>Number of tourists</label><input name="tourist_count" type="number" min="1" max="500" value="1" required></div><div class="field"><label>Entry gate</label><select name="entry_gate" required><option value="">Choose a gate</option>${gateList.filter(g=>g.status==='Active').map(g=>`<option>${esc(g.name)}</option>`).join('')}</select></div></div><div class="form-section" style="margin-top:20px">Vehicle information</div><div class="form-grid"><div class="field"><label>Vehicle type</label><select name="vehicle_type" required><option value="">Choose vehicle type</option>${['Car','Bike','Bus','Auto','Van','Other'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Vehicle number</label><input name="vehicle_number" placeholder="MH12AB1234" style="text-transform:uppercase" required></div><div class="field"><label>Vehicle model <span class="muted">(optional)</span></label><input name="vehicle_model" placeholder="e.g. Swift Dzire"></div></div><footer class="form-footer"><span class="form-helper">⌖ IN date & time and operator are recorded automatically.</span><button class="primary-btn" type="submit" id="entry-submit">Register entry →</button></footer></form></div>` + endPage());
  $('#entry-form').onsubmit=async event=>{event.preventDefault(); const form=event.currentTarget; $$('.field',form).forEach(x=>{x.classList.remove('has-error');$('.field-error',x)?.remove()}); const payload=Object.fromEntries(new FormData(form)); payload.tourist_count=Number(payload.tourist_count); const button=$('#entry-submit'); button.disabled=true; button.textContent='Registering…'; try{const result=await api('/api/visits/entry',{method:'POST',body:JSON.stringify(payload)}); state.dashboard=null; showEntrySuccess(result); toast(result.message);}catch(error){applyFields(form,error.data?.error?.fields);toast(error.message,'error');button.disabled=false;button.textContent='Register entry →';}};
}
function applyFields(form,fields={}){Object.entries(fields).forEach(([key,message])=>{const input=$(`[name="${key}"]`,form);if(input){const holder=input.closest('.field');holder.classList.add('has-error');holder.insertAdjacentHTML('beforeend',`<small class="field-error">${esc(message)}</small>`);}})}
/* Offline QR version 2-L encoder. It carries the opaque, server-validated pass token. */
function drawQRCode(value,canvas){const bytes=[...new TextEncoder().encode(value)];if(bytes.length>32)throw new Error('Pass token is too long for the QR code.');const size=25,m=Array.from({length:size},()=>Array(size).fill(null));const set=(x,y,v)=>{if(x>=0&&y>=0&&x<size&&y<size)m[y][x]=v};const finder=(x,y)=>{for(let dy=-1;dy<=7;dy++)for(let dx=-1;dx<=7;dx++){const inside=dx>=0&&dx<=6&&dy>=0&&dy<=6;set(x+dx,y+dy,inside&&(dx===0||dx===6||dy===0||dy===6||(dx>=2&&dx<=4&&dy>=2&&dy<=4)))}};finder(0,0);finder(size-7,0);finder(0,size-7);for(let i=8;i<size-8;i++){if(m[6][i]===null)set(i,6,i%2===0);if(m[i][6]===null)set(6,i,i%2===0)}for(let y=16;y<=20;y++)for(let x=16;x<=20;x++)set(x,y,Math.max(Math.abs(x-18),Math.abs(y-18))===2||(x===18&&y===18));const formatA=[[8,0],[8,1],[8,2],[8,3],[8,4],[8,5],[8,7],[8,8],[7,8],[5,8],[4,8],[3,8],[2,8],[1,8],[0,8]],formatB=[[24,8],[23,8],[22,8],[21,8],[20,8],[19,8],[18,8],[17,8],[8,18],[8,19],[8,20],[8,21],[8,22],[8,23],[8,24]];[...formatA,...formatB].forEach(([x,y])=>set(x,y,false));set(8,17,true);const bits=[0,1,0,0];for(let i=7;i>=0;i--)bits.push((bytes.length>>i)&1);bytes.forEach(byte=>{for(let i=7;i>=0;i--)bits.push((byte>>i)&1)});for(let i=0;i<Math.min(4,34*8-bits.length);i++)bits.push(0);while(bits.length%8)bits.push(0);const data=[];for(let i=0;i<bits.length;i+=8)data.push(parseInt(bits.slice(i,i+8).join(''),2));for(let i=data.length,pad=0;i<34;i++,pad++)data.push(pad%2?0x11:0xec);const exp=Array(512),log=Array(256);let n=1;for(let i=0;i<255;i++){exp[i]=n;log[n]=i;n<<=1;if(n&0x100)n^=0x11d}for(let i=255;i<512;i++)exp[i]=exp[i-255];const mul=(a,b)=>a&&b?exp[log[a]+log[b]]:0;let generator=[1];for(let i=0;i<10;i++){const next=Array(generator.length+1).fill(0);generator.forEach((v,j)=>{next[j]^=v;next[j+1]^=mul(v,exp[i])});generator=next}let rem=Array(10).fill(0);data.forEach(byte=>{const factor=byte^rem[0];rem=rem.slice(1);rem.push(0);for(let i=0;i<10;i++)rem[i]^=mul(generator[i+1],factor)});const stream=[...data,...rem],codeBits=[];stream.forEach(byte=>{for(let i=7;i>=0;i--)codeBits.push((byte>>i)&1)});let bit=0,up=true;for(let right=size-1;right>0;right-=2){if(right===6)right--;for(let pass=0;pass<size;pass++){const y=up?size-1-pass:pass;for(const x of [right,right-1])if(m[y][x]===null){const raw=codeBits[bit++]||0;set(x,y,Boolean(raw^((x+y)%2===0)))}}up=!up}let format=(1<<3);let remainder=format<<10;const degree=x=>x?Math.floor(Math.log2(x)):0;while(degree(remainder)>=degree(0x537))remainder^=0x537<<(degree(remainder)-degree(0x537));format=((format<<10)|remainder)^0x5412;formatA.forEach(([x,y],i)=>set(x,y,Boolean((format>>i)&1)));formatB.forEach(([x,y],i)=>set(x,y,Boolean((format>>i)&1)));const scale=8,quiet=4;canvas.width=canvas.height=(size+quiet*2)*scale;const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#102e26';for(let y=0;y<size;y++)for(let x=0;x<size;x++)if(m[y][x])ctx.fillRect((x+quiet)*scale,(y+quiet)*scale,scale,scale)}
/* Corrected format-information placement for the QR symbol. Kept separately for easy audit. */
function drawQRCode(value,canvas){
  const payload=[...new TextEncoder().encode(value)];
  if(payload.length>32)throw new Error('Pass token is too long for the QR code.');
  const size=25,modules=Array.from({length:size},()=>Array(size).fill(null));
  const set=(x,y,on)=>{if(x>=0&&y>=0&&x<size&&y<size)modules[y][x]=on};
  const finder=(x,y)=>{for(let dy=-1;dy<=7;dy++)for(let dx=-1;dx<=7;dx++){const inFinder=dx>=0&&dx<7&&dy>=0&&dy<7;set(x+dx,y+dy,inFinder&&(dx===0||dx===6||dy===0||dy===6||(dx>=2&&dx<=4&&dy>=2&&dy<=4)))}};
  finder(0,0);finder(size-7,0);finder(0,size-7);
  for(let index=8;index<size-8;index++){if(modules[6][index]===null)set(index,6,index%2===0);if(modules[index][6]===null)set(6,index,index%2===0)}
  for(let y=16;y<=20;y++)for(let x=16;x<=20;x++)set(x,y,Math.max(Math.abs(x-18),Math.abs(y-18))===2||(x===18&&y===18));
  const formatA=[[8,0],[8,1],[8,2],[8,3],[8,4],[8,5],[8,7],[8,8],[7,8],[5,8],[4,8],[3,8],[2,8],[1,8],[0,8]];
  const formatB=[[24,8],[23,8],[22,8],[21,8],[20,8],[19,8],[18,8],[17,8],[8,18],[8,19],[8,20],[8,21],[8,22],[8,23],[8,24]];
  [...formatA,...formatB].forEach(([x,y])=>set(x,y,false));set(8,17,true);
  const bits=[0,1,0,0];for(let i=7;i>=0;i--)bits.push((payload.length>>i)&1);payload.forEach(byte=>{for(let i=7;i>=0;i--)bits.push((byte>>i)&1)});
  for(let i=0;i<Math.min(4,34*8-bits.length);i++)bits.push(0);while(bits.length%8)bits.push(0);
  const data=[];for(let i=0;i<bits.length;i+=8)data.push(parseInt(bits.slice(i,i+8).join(''),2));for(let i=data.length,pad=0;i<34;i++,pad++)data.push(pad%2?0x11:0xec);
  const exp=Array(512),log=Array(256);let alpha=1;for(let i=0;i<255;i++){exp[i]=alpha;log[alpha]=i;alpha<<=1;if(alpha&0x100)alpha^=0x11d}for(let i=255;i<512;i++)exp[i]=exp[i-255];
  const multiply=(a,b)=>a&&b?exp[log[a]+log[b]]:0;let generator=[1];for(let i=0;i<10;i++){const next=Array(generator.length+1).fill(0);generator.forEach((coefficient,j)=>{next[j]^=coefficient;next[j+1]^=multiply(coefficient,exp[i])});generator=next}
  let remainder=Array(10).fill(0);data.forEach(byte=>{const factor=byte^remainder[0];remainder=remainder.slice(1);remainder.push(0);for(let i=0;i<10;i++)remainder[i]^=multiply(generator[i+1],factor)});
  const stream=[...data,...remainder],codeBits=[];stream.forEach(byte=>{for(let i=7;i>=0;i--)codeBits.push((byte>>i)&1)});
  let bit=0,upward=true;for(let right=size-1;right>0;right-=2){if(right===6)right--;for(let pass=0;pass<size;pass++){const y=upward?size-1-pass:pass;for(const x of [right,right-1])if(modules[y][x]===null){const raw=codeBits[bit++]||0;set(x,y,Boolean(raw^((x+y)%2===0)))}}upward=!upward}
  let format=1<<3,remainderBits=format<<10;const degree=value=>value?Math.floor(Math.log2(value)):0;while(degree(remainderBits)>=degree(0x537))remainderBits^=0x537<<(degree(remainderBits)-degree(0x537));format=((format<<10)|remainderBits)^0x5412;
  formatA.forEach(([x,y],i)=>set(x,y,Boolean((format>>i)&1)));formatB.forEach(([x,y],i)=>set(x,y,Boolean((format>>i)&1)));
  const scale=8,quiet=4;canvas.width=canvas.height=(size+quiet*2)*scale;const context=canvas.getContext('2d');context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);context.fillStyle='#102e26';for(let y=0;y<size;y++)for(let x=0;x<size;x++)if(modules[y][x])context.fillRect((x+quiet)*scale,(y+quiet)*scale,scale,scale);
}
  function passDetails(item){const details=[['Pass ID',item.public_id],['Visitor / group',item.group_name],['Mobile',item.mobile||'Not provided'],['Visitors',num(item.tourist_count)],['Vehicle number',item.vehicle_number],['Vehicle',`${item.vehicle_type}${item.vehicle_model?' · '+item.vehicle_model:''}`],['Purpose','Tourist visit'],['Entry gate',item.entry_gate],['Time in',`${item.in_date} ${item.in_time}`],['Entry operator',item.entry_operator||'Not recorded'],['Status',item.status==='INSIDE'?'Valid until exit is registered':'Visit completed']];if(item.status==='EXITED')details.push(['Exit gate',item.exit_gate||'Not recorded'],['Time out',item.out_date&&item.out_time?`${item.out_date} ${item.out_time}`:'Not recorded'],['Exit operator',item.exit_operator||'Not recorded']);return `<div class="pass-details">${details.map(([label,value])=>`<div><span>${esc(label)}</span><b>${esc(value)}</b></div>`).join('')}</div>`}
function showEntrySuccess(result){const item=result.item;$('#entry-view').innerHTML=`<div class="success-card"><div class="eyebrow">Entry complete</div><h2>${esc(result.message)}</h2><p>Your visitor pass is ready. At exit, the operator scans its QR code—no name, vehicle, or visitor ID needs to be typed again.</p><section class="visitor-pass" id="visitor-pass"><header class="visitor-pass-head"><strong class="pass-type">VISITOR</strong><div class="pass-logo"><span class="brand-mark">⌖</span><span>TOURGUARD</span></div></header><div class="visitor-pass-body"><div class="pass-information">${passDetails(item)}</div><aside class="pass-qr"><b class="pass-qr-title">SCAN AT EXIT</b><canvas id="visitor-pass-qr" class="qr-canvas" aria-label="Scannable exit QR code"></canvas><small>Ser. No. ${esc(item.public_id)}</small></aside></div><footer class="pass-signatures"><div>VISITOR SIGN</div><div>OPERATOR SIGN</div><div>SECURITY OFFICER</div></footer></section><div class="pass-actions"><button class="primary-btn" id="print-pass">▣ Print pass</button><button class="secondary-btn" id="another-entry">Register another entry</button><button class="secondary-btn" id="open-exit">Open exit scanner</button></div></div>`;drawQRCode(result.qr_payload,$('#visitor-pass-qr'));$('#print-pass').onclick=()=>window.print();$('#another-entry').onclick=()=>renderEntry();$('#open-exit').onclick=()=>go('exit')}
function visitorPassMarkup(item){return `<section class="visitor-pass" id="visitor-pass"><header class="visitor-pass-head"><strong class="pass-type">VISITOR</strong><div class="pass-logo"><span class="brand-mark">⌖</span><span>TOURGUARD</span></div></header><div class="visitor-pass-body"><div class="pass-information">${passDetails(item)}</div><aside class="pass-qr"><b class="pass-qr-title">SCAN AT EXIT</b><canvas id="visitor-pass-qr" class="qr-canvas" aria-label="Scannable exit QR code"></canvas><small>Ser. No. ${esc(item.public_id)}</small></aside></div><footer class="pass-signatures"><div>VISITOR SIGN</div><div>OPERATOR SIGN</div><div>SECURITY OFFICER</div></footer></section>`}
function showEntrySuccess(result){const item=result.item;$('#entry-view').innerHTML=`<div class="success-card"><div class="eyebrow">Entry complete</div><h2>${esc(result.message)}</h2><p>Your visitor pass is ready. At exit, the operator scans its QR code—no name, vehicle, or visitor ID needs to be typed again.</p>${visitorPassMarkup(item)}<div class="pass-actions"><button class="primary-btn" id="print-pass">▣ Print pass</button><button class="secondary-btn" id="another-entry">Register another entry</button><button class="secondary-btn" id="open-exit">Open exit scanner</button></div></div>`;drawQRCode(result.qr_payload,$('#visitor-pass-qr'));$('#print-pass').onclick=()=>window.print();$('#another-entry').onclick=()=>renderEntry();$('#open-exit').onclick=()=>go('exit');requestAnimationFrame(()=>$('#visitor-pass')?.scrollIntoView({behavior:'smooth',block:'center'}))}
function showStoredPass(item){if(!item.qr_token)return toast('This record does not contain a saved pass code.','error');$('#pass-preview')?.remove();const preview=document.createElement('div');preview.id='pass-preview';preview.className='pass-preview';preview.innerHTML=`<section class="pass-preview-dialog" role="dialog" aria-modal="true" aria-label="Visitor pass"><button class="secondary-btn" id="close-pass-preview">Close</button>${visitorPassMarkup(item)}<div class="pass-actions"><button class="primary-btn" id="print-saved-pass">▣ Print pass</button></div></section>`;document.body.append(preview);drawQRCode(item.qr_token,$('#visitor-pass-qr',preview));$('#print-saved-pass').onclick=()=>window.print();$('#close-pass-preview').onclick=()=>preview.remove();preview.onclick=event=>{if(event.target===preview)preview.remove()}}
  function historyRowsWithPass(items, inside=false){
    if(!inside)state.passItems=new Map(items.map(item=>[String(item.id),item]));
    return items.map(item=>{
      const passButton=!inside&&isEditor()?`<button class="pass-history-button" type="button" data-pass-id="${esc(item.id)}">View pass</button><br>`:'';
      const exitCell=inside?'':`<td>${item.out_date?`${esc(item.out_date)}<br><span class="muted">${esc(item.out_time)}</span>`:'—'}</td>`;
      return `<tr><td>${passButton}<b class="mono">${esc(item.public_id)}</b><br><span class="muted">${esc(item.group_name)}</span></td><td><b class="mono">${esc(item.vehicle_number)}</b><br><span class="muted">${esc(item.vehicle_type)}</span></td><td>${num(item.tourist_count)}</td><td>${esc(item.in_date)}<br><span class="muted">${esc(item.in_time)}</span></td>${exitCell}<td>${esc(item.duration)}</td><td>${esc(item.entry_gate)}${item.exit_gate?'<br><span class="muted">→ '+esc(item.exit_gate)+'</span>':''}</td><td>${badge(item.status)}</td></tr>`;
    }).join('');
  }

let cameraStream=null,scannerRunning=false;
function stopCameraScanner(){scannerRunning=false;if(cameraStream){cameraStream.getTracks().forEach(track=>track.stop());cameraStream=null}const video=$('#scanner-video');if(video)video.srcObject=null;$('#scanner-empty')?.classList.remove('hidden');const start=$('#start-scanner'),stop=$('#stop-scanner');if(start)start.classList.remove('hidden');if(stop)stop.classList.add('hidden')}
async function loadQrDecoder(){
  if(typeof window.jsQR==='function')return window.jsQR;
  await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/jsqr@1.4.0/dist/jsQR.js';script.onload=resolve;script.onerror=()=>reject(new Error('Could not load the QR scanner. Check your internet connection and try again.'));document.head.append(script)});
  return window.jsQR;
}
async function startCameraScanner(){
  const gate=$('#scanner-gate')?.value;
  if(!gate)return toast('Choose the exit gate before starting the scanner.','warn');
  if(!navigator.mediaDevices?.getUserMedia)return toast('Camera access is not available. Open TourGuard on localhost or HTTPS and allow camera access.','error');
  const status=$('#scanner-status'),video=$('#scanner-video');
  try{
    stopCameraScanner();
    let detector=null,decodeQr=null;
    if('BarcodeDetector' in window){try{detector=new BarcodeDetector({formats:['qr_code']})}catch{}}
    if(!detector)decodeQr=await loadQrDecoder();
    cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});
    video.srcObject=cameraStream;
    await video.play();
    scannerRunning=true;
    $('#scanner-empty').classList.add('hidden');
    $('#start-scanner').classList.add('hidden');
    $('#stop-scanner').classList.remove('hidden');
    status.textContent='Camera is live — hold the visitor pass inside the frame.';
    const scanCanvas=document.createElement('canvas'),scanContext=scanCanvas.getContext('2d',{willReadFrequently:true});
    const scan=async()=>{
      if(!scannerRunning||!video.isConnected)return;
      try{
        let passToken='';
        if(detector){const found=await detector.detect(video);passToken=found[0]?.rawValue||''}
        else if(video.videoWidth){const width=Math.min(video.videoWidth,640),height=Math.round(video.videoHeight*width/video.videoWidth);scanCanvas.width=width;scanCanvas.height=height;scanContext.drawImage(video,0,0,width,height);const image=scanContext.getImageData(0,0,width,height);passToken=decodeQr(image.data,width,height,{inversionAttempts:'dontInvert'})?.data||''}
        if(passToken){stopCameraScanner();status.textContent='Pass recognized. Recording exit…';toast('Pass recognized. Exit is being recorded.');await lookupExit(passToken,true,gate);return}
      }catch{}
      requestAnimationFrame(scan);
    };
    requestAnimationFrame(scan);
  }catch(error){
    stopCameraScanner();
    status.textContent='Camera could not be started.';
    toast(error.name==='NotAllowedError'?'Camera permission was not granted. Allow camera access and try again.':error.message||'Could not access the camera.','error');
  }
}
async function renderExit() { if(!isEditor())return notAllowed('Exit registration requires operator access'); const gateList=await gates(); shell(pageHeader('Touch-free exit','Scan visitor pass','Choose the exit gate once, then scan the QR pass. The visitor can leave without entering any details.')+`<div class="card lookup-panel"><section class="scanner-box"><div class="scanner-view"><video id="scanner-video" muted playsinline></video><div class="scanner-empty" id="scanner-empty">▣<br><small>Camera preview appears here</small></div><div class="scanner-frame"></div></div><div class="scanner-copy"><div class="eyebrow">Camera exit scanner</div><h3>Scan and go</h3><p id="scanner-status">The browser will ask for camera permission only after you start scanning.</p><select id="scanner-gate" aria-label="Scanner exit gate"><option value="">Choose exit gate</option>${gateList.filter(g=>g.status==='Active').map(g=>`<option>${esc(g.name)}</option>`).join('')}</select><div style="display:flex;gap:8px;margin-top:10px"><button class="primary-btn" id="start-scanner">▣ Start camera</button><button class="secondary-btn hidden" id="stop-scanner">Stop</button></div></div></section><div style="display:flex;align-items:center;gap:12px;margin:18px 0 11px"><span class="muted" style="font-size:12px">Scanner unavailable or damaged pass?</span><span style="height:1px;background:var(--line);flex:1"></span></div><div class="lookup-row"><input id="exit-search" placeholder="Manual fallback: vehicle, visitor ID, phone, or pass code"><button class="secondary-btn" id="find-visit">Find active visit</button></div><p class="muted" style="font-size:12px;margin:10px 0 0">A pass is valid only while its visitor record is INSIDE; exited passes cannot be used twice.</p><div id="lookup-result"></div></div>`+endPage()); $('#start-scanner').onclick=startCameraScanner;$('#stop-scanner').onclick=()=>{stopCameraScanner();$('#scanner-status').textContent='Scanner stopped.'};$('#find-visit').onclick=()=>lookupExit($('#exit-search').value);$('#exit-search').onkeydown=e=>{if(e.key==='Enter')lookupExit(e.target.value)}; }
async function lookupExit(raw,autoExit=false,scannerGate=''){const key=raw.trim();if(!key)return toast('Enter a vehicle number, visitor ID, mobile number, or pass code.','warn');const zone=$('#lookup-result');zone.innerHTML='<div class="loading">Looking up active visit…</div>';try{const response=await api(`/api/visits/lookup/${encodeURIComponent(key)}`);if(!response.item){zone.innerHTML='<div class="empty"><div class="empty-icon">⌕</div><b>No active visit found</b><p>The pass may already have been used, or the scan was incomplete.</p></div>';if(autoExit)toast('No active visitor matched this pass.','warn');return}const x=response.item;if(autoExit){zone.innerHTML=`<div class="success-card"><div class="eyebrow">Pass verified</div><h2>${esc(x.vehicle_number)} recognized</h2><p>Registering exit at ${esc(scannerGate)}—the visitor details were read from the pass.</p></div>`;return confirmExit(x.id,scannerGate)}const gatesList=await gates();zone.innerHTML=`<article class="record-card"><div class="record-header"><div><div class="eyebrow">Active visitor</div><h2>${esc(x.vehicle_number)} <span class="mono muted">${esc(x.public_id)}</span></h2></div>${badge(x.status)}</div><div class="detail-grid"><div>Tourist group<b>${esc(x.group_name)}</b></div><div>Vehicle type<b>${esc(x.vehicle_type)}</b></div><div>Tourists<b>${num(x.tourist_count)}</b></div><div>Entered<b>${esc(x.in_date)} · ${esc(x.in_time)}</b></div><div>Duration inside<b>${esc(x.duration)}</b></div><div>Entry gate<b>${esc(x.entry_gate)}</b></div></div><div class="lookup-row"><select id="exit-gate" aria-label="Exit gate"><option value="">Choose exit gate</option>${gatesList.filter(g=>g.status==='Active').map(g=>`<option>${esc(g.name)}</option>`).join('')}</select><button class="primary-btn" id="confirm-exit">Register exit →</button></div></article>`;$('#confirm-exit').onclick=()=>confirmExit(x.id,$('#exit-gate').value)}catch(error){zone.innerHTML=`<div class="empty">${esc(error.message)}</div>`}}
async function confirmExit(id,exit_gate){if(!exit_gate)return toast('Choose the exit gate first.','warn');const btn=$('#confirm-exit');btn.disabled=true;btn.textContent='Saving…';try{const result=await api(`/api/visits/${id}/exit`,{method:'POST',body:JSON.stringify({exit_gate})});toast(result.message);state.dashboard=null;$('#lookup-result').innerHTML=`<div class="success-card"><div class="eyebrow">Exit complete</div><h2>${esc(result.item.vehicle_number)} is now marked exited.</h2><p>Visit duration: <b>${esc(result.item.duration)}</b> · Exit recorded at ${esc(result.item.out_time)}.</p><button class="primary-btn" id="new-exit" style="margin-top:15px">Process another exit</button></div>`;$('#new-exit').onclick=()=>renderExit()}catch(error){toast(error.message,'error');btn.disabled=false;btn.textContent='Register exit →'}}

function tableRows(items, inside=false){return items.map(x=>`<tr><td><b class="mono">${esc(x.public_id)}</b><br><span class="muted">${esc(x.group_name)}</span></td><td><b class="mono">${esc(x.vehicle_number)}</b><br><span class="muted">${esc(x.vehicle_type)}</span></td><td>${num(x.tourist_count)}</td><td>${esc(x.in_date)}<br><span class="muted">${esc(x.in_time)}</span></td>${inside?'':`<td>${x.out_date?esc(x.out_date)+'<br><span class="muted">'+esc(x.out_time)+'</span>':'—'}</td>`}<td>${esc(x.duration)}</td><td>${esc(x.entry_gate)}${x.exit_gate?'<br><span class="muted">→ '+esc(x.exit_gate)+'</span>':''}</td><td>${badge(x.status)}</td></tr>`).join('')}
async function renderInside() { const result=await api('/api/visits/inside?limit=50'); shell(pageHeader('Live occupancy','Currently inside','Only active records appear here. Durations refresh automatically.',`${isEditor()?'<button class="primary-btn" data-go="entry">＋ Register entry</button>':''}`)+`<div class="card"><div class="filters"><input id="inside-search" placeholder="Search active vehicle, visitor ID or group"><select id="inside-type"><option value="">All vehicle types</option>${['Car','Bike','Bus','Auto','Van','Other'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Visit / group</th><th>Vehicle</th><th>Guests</th><th>Entry</th><th>Duration inside</th><th>Gate</th><th>Status</th></tr></thead><tbody id="inside-rows">${result.items.length?tableRows(result.items,true):'<tr><td colspan="7"><div class="empty">No visitors are currently inside.</div></td></tr>'}</tbody></table></div><div class="pagination"><span>${result.total} active visit${result.total===1?'':'s'} · live duration shown</span><span>Updates automatically</span></div></div>`+endPage()); $$('[data-go]').forEach(x=>x.onclick=()=>go(x.dataset.go)); let timer; const filter=()=>{clearTimeout(timer);timer=setTimeout(async()=>{const term=$('#inside-search').value,kind=$('#inside-type').value;const r=await api(`/api/visits/inside?limit=50&search=${encodeURIComponent(term)}&vehicle_type=${encodeURIComponent(kind)}`);$('#inside-rows').innerHTML=r.items.length?tableRows(r.items,true):'<tr><td colspan="7"><div class="empty">No matching active visits.</div></td></tr>';},220)};$('#inside-search').oninput=filter;$('#inside-type').onchange=filter; }

async function renderHistory(initial={}) { const make=async(params={})=>{const query=new URLSearchParams({limit:10,...initial,...params});const result=await api('/api/visits?'+query);const gatesList=await gates();shell(pageHeader('Operations archive','Visitor history','Search and filter every entry permanently retained in the database.',`<button class="secondary-btn" id="export-csv">⇩ CSV</button><button class="secondary-btn" id="print-report">▣ Print</button>`)+`<div class="card"><div class="filters"><input id="history-search" placeholder="Search visitor, vehicle, phone or name" value="${esc(query.get('search')||'')}"><select id="history-status"><option value="">All statuses</option><option value="INSIDE" ${query.get('status')==='INSIDE'?'selected':''}>Inside</option><option value="EXITED" ${query.get('status')==='EXITED'?'selected':''}>Exited</option></select><select id="history-type"><option value="">All vehicles</option>${['Car','Bike','Bus','Auto','Van','Other'].map(x=>`<option ${query.get('vehicle_type')===x?'selected':''}>${x}</option>`).join('')}</select><select id="history-gate"><option value="">All gates</option>${gatesList.map(x=>`<option ${query.get('gate')===x.name?'selected':''}>${esc(x.name)}</option>`).join('')}</select></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Visit / group</th><th>Vehicle</th><th>Guests</th><th>In</th><th>Out</th><th>Duration</th><th>Gates</th><th>Status</th></tr></thead><tbody>${result.items.length?tableRows(result.items):'<tr><td colspan="8"><div class="empty"><div class="empty-icon">⌕</div>No matching visits.</div></td></tr>'}</tbody></table></div><footer class="pagination"><span>${result.total} matching visit${result.total===1?'':'s'}</span><div class="actions"><button class="secondary-btn" ${result.page<=1?'disabled':''} id="prev-page">← Previous</button><span style="padding:8px">${result.page} / ${result.pages}</span><button class="secondary-btn" ${result.page>=result.pages?'disabled':''} id="next-page">Next →</button></div></footer></div>`+endPage()); const getFilters=()=>({search:$('#history-search').value,status:$('#history-status').value,vehicle_type:$('#history-type').value,gate:$('#history-gate').value});let wait;$('#history-search').oninput=()=>{clearTimeout(wait);wait=setTimeout(()=>make(getFilters()),260)};['history-status','history-type','history-gate'].forEach(id=>$('#'+id).onchange=()=>make(getFilters()));$('#prev-page').onclick=()=>make({...getFilters(),page:result.page-1});$('#next-page').onclick=()=>make({...getFilters(),page:result.page+1});$('#print-report').onclick=()=>window.print();$('#export-csv').onclick=()=>exportCsv(result.items);};return make(); }
function exportCsv(items){const headers=['Visitor ID','Group','Tourists','Vehicle','Vehicle type','In date','In time','Out date','Out time','Duration','Entry gate','Exit gate','Status'];const rows=[headers,...items.map(x=>[x.public_id,x.group_name,x.tourist_count,x.vehicle_number,x.vehicle_type,x.in_date,x.in_time,x.out_date||'',x.out_time||'',x.duration,x.entry_gate,x.exit_gate||'',x.status])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`tourguard-history-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href);toast('CSV export is ready.');}

async function renderVehicles(){const response=await api('/api/vehicles');shell(pageHeader('Vehicle database','Vehicles','Every return visit stays connected to the same vehicle record.')+`<div class="card"><div class="filters"><input id="vehicle-search" placeholder="Search vehicle number"><span class="muted" style="padding:8px">${response.items.length} known vehicles</span></div><div class="list-card" id="vehicle-list">${vehicleList(response.items)}</div></div>`+endPage());$('#vehicle-search').oninput=e=>{const q=e.target.value.toUpperCase();$('#vehicle-list').innerHTML=vehicleList(response.items.filter(v=>v.number.includes(q)));};}
function vehicleList(items){return items.length?items.map(v=>`<div class="vehicle-row"><div class="vehicle-kind">${vehicleIcon(v.vehicle_type)}</div><div><b class="mono">${esc(v.number)}</b><small>${esc(v.vehicle_type)}${v.model?' · '+esc(v.model):''} · ${v.total_visits} visit${v.total_visits===1?'':'s'}</small></div><div class="vehicle-status">${badge(v.current_status)}<small>Last: ${dateTime(v.last_visit_at)}</small></div></div>`).join(''):'<div class="empty">No vehicles match this search.</div>'}

async function renderParking(){const data=await api('/api/parking');const editable=isAdmin();shell(pageHeader('Capacity control','Parking management','Occupancy is calculated directly from vehicles that are currently inside.',editable?'<button class="primary-btn" id="save-parking">Save capacities</button>':'')+`<div class="split-grid"><section class="card"><div class="card-head"><div><h2>Live parking occupancy</h2><p>Updates with every entry and exit</p></div></div><div class="parking-list">${data.items.map(parkingRow).join('')}</div></section><section class="card form-card"><div class="form-section">Parking capacity</div><p class="muted" style="margin-top:0">${editable?'Adjust the available parking slots for each vehicle type.':'Only an administrator can edit these capacities.'}</p>${data.items.map(p=>`<div class="settings-row"><div><b>${esc(p.vehicle_type)} parking</b><small>${p.occupied} currently occupied</small></div><input type="number" min="0" data-capacity="${esc(p.vehicle_type)}" value="${p.capacity}" ${editable?'':'disabled'}></div>`).join('')}</section></div>`+endPage());if(editable)$('#save-parking').onclick=async()=>{const capacities={};$$('[data-capacity]').forEach(x=>capacities[x.dataset.capacity]=Number(x.value));try{await api('/api/parking',{method:'PUT',body:JSON.stringify({capacities})});toast('Parking capacities saved.');state.dashboard=null;renderParking()}catch(e){toast(e.message,'error')}};}

async function renderAnalytics(){const data=await api('/api/analytics');shell(pageHeader('Operational intelligence','Analytics','Charts are computed from actual records currently stored in your database.')+`<div class="metric-grid">${metric('Tracked entry hours',data.hourly.filter(x=>x.value).length,'◷','Hours with recorded activity')}${metric('7-day visitors',data.daily.reduce((a,x)=>a+x.value,0),'◉','From recorded visits')}${metric('Vehicle records',data.vehicles.reduce((a,x)=>a+x.value,0),'▱','All stored visits')}${metric('Peak hour',data.hourly.reduce((a,x)=>a.value>x.value?a:x).label,'↗','Current historical peak')}</div><div class="content-grid"><section class="card chart-card"><div class="card-head"><div><h2>Visitors by day</h2><p>Latest seven-day window</p></div></div>${barChart(data.daily)}</section><section class="card chart-card"><div class="card-head"><div><h2>Vehicle type distribution</h2><p>All recorded vehicle visits</p></div></div>${barChart(data.vehicles)}</section></div><div class="card chart-card" style="margin-top:17px"><div class="card-head"><div><h2>Visitors by month</h2><p>Historical entry trend</p></div></div>${barChart(data.monthly)}</div>`+endPage());}

async function renderAI(){const data=await api('/api/ai/insights');let body;if(!data.ready){body=`<div class="card empty"><div class="empty-icon">✦</div><b>Learning from your operation</b><p>${esc(data.message)}</p></div>`}else{const p=data.prediction;body=`<section class="card ai-hero"><div class="eyebrow" style="color:#c8ef70">Model-supported planning</div><h2>Tomorrow’s operational outlook</h2><p>Forecasts use the historical visit records in this database. They are planning signals, not automatic decisions.</p><div class="prediction-grid"><div class="prediction"><span>Expected visitors</span><b>${num(p.expected_visitors)}</b></div><div class="prediction"><span>Expected peak</span><b>${esc(p.peak_time)}</b></div><div class="prediction"><span>Crowd level</span><b>${esc(p.crowd_level)}</b></div><div class="prediction"><span>Parking demand</span><b>${esc(p.parking_demand)}</b></div></div></section><section class="card" style="margin-top:17px"><div class="card-head"><div><h2>Insights from real records</h2><p>Generated only when enough visit history exists</p></div></div><ul class="insight-list">${data.insights.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`}shell(pageHeader('AI workspace','AI insights','Grounded in your recorded visitor and vehicle data.')+body+endPage());}

async function renderReports(){const today=new Date().toISOString().slice(0,10);const load=async()=>{const start=$('#report-start')?.value||today,end=$('#report-end')?.value||today;const r=await api(`/api/reports?date_from=${start}&date_to=${end}`);const html=pageHeader('Exportable summaries','Reports','Generate a focused operational snapshot from the date range you select.',`<button class="secondary-btn" id="report-print">▣ Print</button><button class="primary-btn" id="report-csv">⇩ Export CSV</button>`)+`<div class="card form-card"><div class="form-grid"><div class="field"><label>From date</label><input id="report-start" type="date" value="${esc(start)}"></div><div class="field"><label>To date</label><input id="report-end" type="date" value="${esc(end)}"></div></div><button class="secondary-btn" id="run-report">Run report</button></div><div class="metric-grid" style="margin-top:17px">${metric('Total visitors',r.total_visitors,'◉','In selected range')}${metric('Vehicle entries',r.total_vehicles,'▱','In selected range')}${metric('Completed exits',r.total_exits,'⇥','In selected range')}${metric('Peak time',r.peak_time,'◷','Based on entry records')}</div><section class="card" style="margin-top:17px"><div class="card-head"><div><h2>Vehicle type distribution</h2><p>${esc(r.range.from)} to ${esc(r.range.to)}</p></div></div><div class="parking-list">${r.vehicle_distribution.length?r.vehicle_distribution.map(x=>`<div class="parking-row"><header><span>${esc(x.vehicle_type)}</span><span>${x.count} visits</span></header><div class="progress"><i style="width:${Math.min(100,x.count/Math.max(...r.vehicle_distribution.map(y=>y.count),1)*100)}%"></i></div></div>`).join(''):'<div class="empty">No visits in this date range.</div>'}</div></section>`+endPage();shell(html);$('#run-report').onclick=load;$('#report-print').onclick=()=>window.print();$('#report-csv').onclick=()=>exportCsv([]);};return load();}

async function renderNotifications(){const data=await api('/api/notifications');shell(pageHeader('System centre','Notifications','Warnings, crowd notices, and operational events appear here.')+`<div class="card"><div class="alert-list">${data.items.length?data.items.map(n=>`<article class="alert"><div class="alert-symbol">${n.severity==='critical'?'⚠':n.severity==='warning'?'!':'i'}</div><div><b>${esc(n.title)}</b><p>${esc(n.message)}</p><small class="muted">${dateTime(n.created_at)}${n.read_at?' · Read':''}</small></div>${!n.read_at?`<button class="secondary-btn" data-read="${n.id}">Mark read</button>`:''}</article>`).join(''):'<div class="empty">No notifications yet.</div>'}</div></div>`+endPage());$$('[data-read]').forEach(btn=>btn.onclick=async()=>{await api(`/api/notifications/${btn.dataset.read}/read`,{method:'POST',body:'{}'});renderNotifications()});}

async function renderUsers(){if(!isAdmin())return notAllowed();const data=await api('/api/users');shell(pageHeader('Access control','User management','Create role-scoped accounts for administrators, gate operators, and viewers.',`<button class="primary-btn" id="show-user-form">＋ Add user</button>`)+`<div class="card hidden" id="user-form-card" style="margin-bottom:17px"><form class="form-card" id="user-form"><div class="form-grid"><div class="field"><label>Name</label><input name="name" required></div><div class="field"><label>Email</label><input name="email" type="email" required></div><div class="field"><label>Temporary password</label><input name="password" type="password" minlength="8" required></div><div class="field"><label>Role</label><select name="role"><option value="operator">Gate Operator</option><option value="viewer">Viewer / Manager</option><option value="admin">Administrator</option></select></div></div><button class="primary-btn">Create secure account</button></form></div><div class="card"><div class="table-wrap"><table class="data-table"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Account status</th><th>Created</th></tr></thead><tbody>${data.items.map(u=>`<tr><td><b>${esc(u.name)}</b></td><td>${esc(u.email)}</td><td>${esc(roleName(u.role))}</td><td>${u.active?badge('Active'):badge('Inactive')}</td><td>${dateTime(u.created_at)}</td></tr>`).join('')}</tbody></table></div></div>`+endPage());$('#show-user-form').onclick=()=>$('#user-form-card').classList.remove('hidden');$('#user-form').onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.currentTarget));try{const x=await api('/api/users',{method:'POST',body:JSON.stringify(p)});toast(x.message);renderUsers()}catch(err){toast(err.message,'error')}}}

async function renderSettings(){if(!isAdmin())return notAllowed();const [settings,gatesList]=await Promise.all([api('/api/settings'),gates()]);shell(pageHeader('System configuration','Settings','Manage capacity thresholds and the gates available to operators.')+`<div class="split-grid"><section class="card form-card"><div class="form-section">Crowd capacity</div><p class="muted">The dashboard calculates crowd level against this maximum tourist capacity.</p><div class="field"><label>Maximum tourist capacity</label><input id="max-capacity" type="number" min="1" value="${esc(settings.max_tourist_capacity)}"></div><button class="primary-btn" id="save-capacity">Save capacity</button></section><section class="card form-card"><div class="form-section">Gate directory</div><p class="muted">Active gates are available on entry and exit forms.</p><div id="gate-list">${gatesList.map(g=>`<div class="settings-row"><div><b>${esc(g.name)}</b><small>Created ${dateTime(g.created_at)}</small></div>${badge(g.status)}</div>`).join('')}</div><form id="gate-form" class="lookup-row" style="margin-top:14px"><input name="name" placeholder="New gate name" required><button class="secondary-btn">Add gate</button></form></section></div>`+endPage());$('#save-capacity').onclick=async()=>{try{await api('/api/settings',{method:'PUT',body:JSON.stringify({max_tourist_capacity:Number($('#max-capacity').value)})});toast('Capacity setting saved.');state.dashboard=null}catch(e){toast(e.message,'error')}};$('#gate-form').onsubmit=async e=>{e.preventDefault();try{const x=await api('/api/gates',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});toast(x.message);state.gates=[];renderSettings()}catch(err){toast(err.message,'error')}}}

tableRows=historyRowsWithPass;
(async()=>{ if(state.token) connectStream(); await render(); })();
